# Importações

Como sempre, utilizaremos algumas bibliotecas para realizar o trabalho.

In [2]:
import pandas as pd
import numpy as np

---

# Extraindo Informações - Candidatos

Por conta da falta de informações extraíveis dos candidatos, acabamos optando por extraír:

1. **Quantidade de Instâncias**
2. **Candidatos por Estado**:
    - Quantidade de candidatos para governador por estado
    - Média da quantidade de candidatos
    - Desvio Padrão da quantidade de candidatos
3. **Candidatos por Partido**:
    - Quantidade de candidatos para governador por partido
    - Média da quantidade de partidos
    - Desvio Padrão da quantidade de partidos

In [16]:
df = pd.read_csv('Resultados\\Candidatos.csv', delimiter=',', encoding='utf-8')
df.head()

,ANO_ELEICAO,SG_UF,DS_CARGO,SQ_CANDIDATO,NM_CANDIDATO,NR_PARTIDO,SG_PARTIDO,PASSOU_TURNO
0,2022,BA,GOVERNADOR,50001609248,ANTONIO CARLOS PEIXOTO DE MAGALHÃES NETO,44,UNIÃO,True
1,2022,PB,GOVERNADOR,150001621388,PEDRO OLIVEIRA CUNHA LIMA,45,PSDB,True
2,2022,SC,GOVERNADOR,240001611127,JORGINHO DOS SANTOS MELLO,22,PL,True
3,2022,MS,GOVERNADOR,120001714229,RENAN BARBOSA CONTAR,28,PRTB,True
4,2022,SC,GOVERNADOR,240001647445,DÉCIO NERY DE LIMA,13,PT,True

### Quantidade de Instâncias

In [27]:
total = df['SQ_CANDIDATO'].count()
print('Quantidade total de candidatos:', total)

Quantidade total de candidatos: 224

### Quantidade por Estado

In [37]:
uf = df['SG_UF'].value_counts()

uf_counts = uf.reset_index()
uf_counts.columns = ['SG_UF', 'COUNT']

In [36]:
uf_mean = uf.mean()
uf_std = uf.std()

Média da quantidade de candidatos por estado: 8.30
Desvio padrão da quantidade de candidatos por estado: 1.96

In [38]:
print(f"Média da quantidade de candidatos por estado: {uf_mean:.2f}")
print(f"Desvio padrão da quantidade de candidatos por estado: {uf_std:.2f}")
print('Quantidade total de candidatos por estado:')
uf_counts

Média da quantidade de candidatos por estado: 8.30
Desvio padrão da quantidade de candidatos por estado: 1.96
Quantidade total de candidatos por estado:

   SG_UF  COUNT
0     RS     12
1     DF     12
2     PE     11
3     SP     10
4     MG     10
5     SC     10
6     SE      9
7     RJ      9
8     RN      9
9     PA      9
10    PI      9
11    MA      9
12    GO      9
13    PR      9
14    TO      8
15    MS      8
16    AM      8
17    PB      8
18    RO      7
19    ES      7
20    AL      7
21    AC      7
22    BA      6
23    AP      6
24    CE      6
25    RR      5
26    MT      4

### Quantidade por Partido

In [39]:
partido = df['SG_PARTIDO'].value_counts()

partido_counts = uf.reset_index()
partido_counts.columns = ['SG_PARTIDO', 'COUNT']

In [40]:
partido_mean = partido.mean()
partido_std = partido.std()

In [41]:
print(f"Média da quantidade de partidos por estado: {partido_mean:.2f}")
print(f"Desvio padrão da quantidade de partidos por estado: {partido_std:.2f}")
print('Quantidade total de candidatos por partido:')
partido_counts

Média da quantidade de partidos por estado: 7.47
Desvio padrão da quantidade de partidos por estado: 4.97
Quantidade total de candidatos por partido:

   SG_PARTIDO  COUNT
0          RS     12
1          DF     12
2          PE     11
3          SP     10
4          MG     10
5          SC     10
6          SE      9
7          RJ      9
8          RN      9
9          PA      9
10         PI      9
11         MA      9
12         GO      9
13         PR      9
14         TO      8
15         MS      8
16         AM      8
17         PB      8
18         RO      7
19         ES      7
20         AL      7
21         AC      7
22         BA      6
23         AP      6
24         CE      6
25         RR      5
26         MT      4

---

# Extraindo Informações - Votos

Com mais quantidade de informações na tabela de votos, extraímos:

1. **Quantidade de Instâncias**
2. **Candidatos por Estado**:
    - Quantidade de candidatos para governador por estado
    - Média da quantidade de candidatos
    - Desvio Padrão da quantidade de candidatos
3. **Candidatos por Partido**:
    - Quantidade de candidatos para governador por partido
    - Média da quantidade de partidos
    - Desvio Padrão da quantidade de partidos