## Importações

Como sempre, utilizaremos algumas bibliotecas para realizar o trabalho.

In [1]:
import pandas as pd
import numpy as np

## Funções Auxiliares

In [16]:
def calcula_estatisticas(dado):
    return {
        'mean': dado.mean(),
        'std': dado.std(),
        'min': dado.min(),
        'max': dado.max(),
        'mode': dado.mode().iloc[0] if not dado.mode().empty else None,
        'quartis': dado.quantile([0.25, 0.5, 0.75])
    }

In [40]:
def estatisticas_turno(df, nome):
    resultados = {}
    
    for n in df[nome].unique():
        df_n = df[df[nome] == n]
        
        for turno in [1, 2, 'ambos']:
            if turno != 'ambos':
                df_turno = df_n[df_n['NR_TURNO'] == turno]
            else:
                df_turno = df_n
            
            votos = df_turno['QT_VOTOS']
            votos_summary = calcula_estatisticas(votos)
            
            resultados[(n, turno)] = votos_summary
    
    return resultados

---

# Extraindo Informações - Candidatos

1. **Quantidade de Instâncias**
2. **Candidatos por Estado:**
    - Quantidade de candidatos para governador por estado
    - Média da quantidade de candidatos por estado
    - Desvio padrão da quantidade de candidatos por estado
    - Moda da quantidade de candidatos por estado
    - Valor mínimo e máximo da quantidade de candidatos por estado
    - Quartis (1º, 2º - mediana, e 3º) da quantidade de candidatos por estado
3. **Candidatos por Partido:**
    - Quantidade de candidatos para governador por partido
    - Média da quantidade de candidatos por partido
    - Desvio padrão da quantidade de candidatos por partido
    - Moda da quantidade de candidatos por partido
    - Valor mínimo e máximo da quantidade de candidatos por partido
    - Quartis (1º, 2º - mediana, e 3º) da quantidade de candidatos por partido

In [3]:
df = pd.read_csv('Resultados\\Candidatos.csv', delimiter=',', encoding='utf-8')
df.head()

,ANO_ELEICAO,SG_UF,DS_CARGO,SQ_CANDIDATO,NM_CANDIDATO,NR_PARTIDO,SG_PARTIDO,PASSOU_TURNO
0,2022,BA,GOVERNADOR,50001609248,ANTONIO CARLOS PEIXOTO DE MAGALHÃES NETO,44,UNIÃO,True
1,2022,PB,GOVERNADOR,150001621388,PEDRO OLIVEIRA CUNHA LIMA,45,PSDB,True
2,2022,SC,GOVERNADOR,240001611127,JORGINHO DOS SANTOS MELLO,22,PL,True
3,2022,MS,GOVERNADOR,120001714229,RENAN BARBOSA CONTAR,28,PRTB,True
4,2022,SC,GOVERNADOR,240001647445,DÉCIO NERY DE LIMA,13,PT,True

### Quantidade de Instâncias

In [4]:
total = df['SQ_CANDIDATO'].count()
print('Quantidade total de instâncias de candidatos:', total)

Quantidade total de instâncias de candidatos: 224

### Quantidade por Estado

In [6]:
uf = df['SG_UF'].value_counts()

uf_counts = uf.reset_index()
uf_counts.columns = ['SG_UF', 'COUNT']

uf_summary = calcula_estatisticas(uf)

In [7]:
print(f"Média: {uf_summary['mean']:.2f}")
print(f"Desvio: {uf_summary['std']:.2f}")
print(f"Valor mínimo: {uf_summary['min']:.2f}")
print(f"Quartil 2: {uf_summary['quartis'][0.25]:.2f}")
print(f"Mediana: {uf_summary['quartis'][0.5]:.2f}")
print(f"Quartil 3: {uf_summary['quartis'][0.75]:.2f}")
print(f"Valor máximo: {uf_summary['max']:.2f}")
print(f"Moda: {uf_summary['mode']}")
print('Quantidade total de candidatos por estado:')
uf_counts

Média: 8.30
Desvio: 1.96
Valor mínimo: 4.00
Quartil 2: 7.00
Mediana: 9.00
Quartil 3: 9.00
Valor máximo: 12.00
Moda: 9
Quantidade total de candidatos por estado:

   SG_UF  COUNT
0     RS     12
1     DF     12
2     PE     11
3     SP     10
4     MG     10
5     SC     10
6     SE      9
7     RJ      9
8     RN      9
9     PA      9
10    PI      9
11    MA      9
12    GO      9
13    PR      9
14    TO      8
15    MS      8
16    AM      8
17    PB      8
18    RO      7
19    ES      7
20    AL      7
21    AC      7
22    BA      6
23    AP      6
24    CE      6
25    RR      5
26    MT      4

### Quantidade por Partido

In [8]:
partido = df['SG_PARTIDO'].value_counts()

partido_counts = partido.reset_index()
partido_counts.columns = ['SG_PARTIDO', 'COUNT']

partido_summary = calcula_estatisticas(partido)

In [9]:
print(f"Média: {partido_summary['mean']:.2f}")
print(f"Desvio: {partido_summary['std']:.2f}")
print(f"Valor mínimo: {partido_summary['min']:.2f}")
print(f"Quartil 2: {partido_summary['quartis'][0.25]:.2f}")
print(f"Mediana: {partido_summary['quartis'][0.5]:.2f}")
print(f"Quartil 3: {partido_summary['quartis'][0.75]:.2f}")
print(f"Valor máximo: {partido_summary['max']:.2f}")
print(f"Moda: {partido_summary['mode']}")
print('Quantidade total de candidatos por partido:')
partido_counts

Média: 7.47
Desvio: 4.97
Valor mínimo: 1.00
Quartil 2: 3.00
Mediana: 7.00
Quartil 3: 10.75
Valor máximo: 20.00
Moda: 3
Quantidade total de candidatos por partido:

       SG_PARTIDO  COUNT
0            PSOL     20
1            PSTU     17
2             PCO     16
3              PL     14
4              PT     13
5           UNIÃO     12
6             PCB     11
7             PSD     11
8             PDT     10
9             MDB      9
10           PSDB      8
11  SOLIDARIEDADE      7
12            PSB      7
13           PRTB      7
14           NOVO      7
15            PMB      7
16             DC      7
17             UP      6
18             PP      5
19           AGIR      4
20            PTB      4
21   REPUBLICANOS      3
22             PV      3
23            PMN      3
24           PODE      3
25            PSC      3
26           PROS      3
27       PATRIOTA      2
28           REDE      1
29      CIDADANIA      1

---

# Extraindo Informações - Votos

Com mais quantidade de informações na tabela de votos, extraímos:

1. **Quantidade de Instâncias**
2. **Votos (Geral)**:
    - Quantidade de votos para governador
    - Média da votos de candidatos
    - Desvio padrão da quantidade de votos
    - Moda da quantidade de votos
    - Valor mínimo e máximo da quantidade de votos
    - Quartis (1º, 2º - mediana, e 3º) da quantidade de votos
3. **Votos por Estado (Turno 1 e Turno 2 e Ambos)**:
    - Quantidade de votos para governador por estado
    - Média da votos de candidatos por estado
    - Desvio padrão da quantidade de votos por estado
    - Moda da quantidade de votos por estado
    - Valor mínimo e máximo da quantidade de votos por estado
    - Quartis (1º, 2º - mediana, e 3º) da quantidade de votos por estado

In [42]:
df = pd.read_csv('Resultados\\Votos.csv', delimiter=',', encoding='utf-8')
df.head()

   ANO_ELEICAO  NR_TURNO SG_UF    DS_CARGO  NR_VOTAVEL  QT_VOTOS  SQ_CANDIDATO
0         2022         1    AC  GOVERNADOR          50         1   10001595336
1         2022         1    AC  GOVERNADOR          50         2   10001595336
2         2022         1    AC  GOVERNADOR          50         1   10001595336
3         2022         1    AC  GOVERNADOR          50         2   10001595336
4         2022         1    AC  GOVERNADOR          50         1   10001595336

### Quantidade de Instâncias

In [11]:
total = df['SQ_CANDIDATO'].count()
print('Quantidade total de instâncias de votos:', total)

Quantidade total de instâncias de votos: 4404307

### Votos (Geral)

In [12]:
votos = df['QT_VOTOS']

votos_counts = df['QT_VOTOS'].value_counts().reset_index()
votos_counts.columns = ['QT_VOTOS', 'COUNT']

votos_summary = calcula_estatisticas(votos)

In [13]:
print(f"Média: {votos_summary['mean']:.2f}")
print(f"Desvio: {votos_summary['std']:.2f}")
print(f"Valor mínimo: {votos_summary['min']:.2f}")
print(f"Quartil 2: {votos_summary['quartis'][0.25]:.2f}")
print(f"Mediana: {votos_summary['quartis'][0.5]:.2f}")
print(f"Quartil 3: {votos_summary['quartis'][0.75]:.2f}")
print(f"Valor máximo: {votos_summary['max']:.2f}")
print(f"Moda: {votos_summary['mode']}")
print('Quantidade total de votos:')
votos_counts

Média: 42.98
Desvio: 51.15
Valor mínimo: 1.00
Quartil 2: 6.00
Mediana: 19.00
Quartil 3: 69.00
Valor máximo: 399.00
Moda: 1
Quantidade total de votos:

     QT_VOTOS   COUNT
0           1  458782
1           2  224363
2           3  152676
3           4  125259
4           5  112651
..        ...     ...
347       344       1
348       364       1
349       399       1
350       394       1
351       359       1

[352 rows x 2 columns]

### Votos por Estado (Turno 1, Turno 2 e Ambos)

In [31]:
estatisticas_votos_uf = estatisticas_turno(df, 'SG_UF')

data = []

for (estado, turno), votos_summary in estatisticas_votos_uf.items():
    data.append({
        'Estado': estado,
        'Turno': turno,
        'Média': votos_summary['mean'],
        'Desvio': votos_summary['std'],
        'Min': votos_summary['min'],
        'Quartil 1': votos_summary['quartis'][0.25],
        'Mediana': votos_summary['quartis'][0.5],
        'Quartil 3': votos_summary['quartis'][0.75],
        'Máximo': votos_summary['max'],
        'Moda': votos_summary['mode']
    })
    
df_estatisticas = pd.DataFrame(data)

In [38]:
df_estatisticas = df_estatisticas.dropna(subset=['Média', 'Desvio', 'Min', 'Quartil 1', 'Mediana', 'Quartil 3', 'Máximo', 'Moda'], how='all')
df_estatisticas = df_estatisticas.drop_duplicates(subset=['Estado', 'Média', 'Desvio'], keep='first')
df_estatisticas.head()

,Estado,Turno,Média,Desvio,Min,Quartil 1,Mediana,Quartil 3,Máximo,Moda
0,AC,1,29.441981,39.935231,1.0,4.0,11.0,37.0,245.0,1.0
3,AL,1,37.819732,39.307648,1.0,9.0,25.0,53.0,263.0,1.0
4,AL,2,67.385241,62.725716,1.0,12.0,36.0,117.0,284.0,5.0
5,AL,ambos,48.370836,50.974445,1.0,10.0,27.0,77.0,284.0,1.0
6,AM,1,34.824875,39.583716,1.0,5.0,19.0,53.0,309.0,1.0